/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClosingDialog: typeof import('./src/components/pos/ClosingDialog.vue')['default']
    CouponsModal: typeof import('./src/components/pos/CouponsModal.vue')['default']
    Customer: typeof import('./src/components/pos/Customer.vue')['default']
    Drafts: typeof import('./src/components/pos/Drafts.vue')['default']
    EnhancedEmptyState: typeof import('./src/components/pos/EnhancedEmptyState.vue')['default']
    Invoice: typeof import('./src/components/pos/Invoice.vue')['default']
    ItemsSelector: typeof import('./src/components/pos/ItemsSelector.vue')['default']
    MpesaPayments: typeof import('./src/components/pos/Mpesa-Payments.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewAddress: typeof import('./src/components/pos/NewAddress.vue')['default']
    OffersModal: typeof import('./src/components/pos/OffersModal.vue')['default']
    OpeningDialog: typeof import('./src/components/pos/OpeningDialog.vue')['default']
    PaidInvoice: typeof import('./src/components/pos/PaidInvoice.vue')['default']
    Pay: typeof import('./src/components/payments/Pay.vue')['default']
    Payments: typeof import('./src/components/pos/Payments.vue')['default']
    Pos: typeof import('./src/components/pos/Pos.vue')['default']
    PosCoupons: typeof import('./src/components/pos/PosCoupons.vue')['default']
    PosOffers: typeof import('./src/components/pos/PosOffers.vue')['default']
    Returns: typeof import('./src/components/pos/Returns.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesOrders: typeof import('./src/components/pos/SalesOrders.vue')['default']
    UpdateCustomer: typeof import('./src/components/pos/UpdateCustomer.vue')['default']
    Variants: typeof import('./src/components/pos/Variants.vue')['default']
  }
}
