# Copyright (c) 2021, Youssef Restom and Contributors
# See license.txt

import frappe
from frappe.tests.utils import FrappeTestCase

from pospire.pospire.doctype.referral_code.referral_code import create_referral_code
from pospire.pospire.tests.test_utils import (
	create_test_pos_offer,
	ensure_test_company,
	ensure_test_customer,
)

# Skip ERPNext test record bootstrapping — tests create their own fixtures
test_ignore = ["Company", "Customer", "POS Offer", "Campaign"]


class TestReferralCode(FrappeTestCase):
	@classmethod
	def setUpClass(cls):
		super().setUpClass()
		cls.company = ensure_test_company()
		cls.customer = ensure_test_customer()
		cls.offer = create_test_pos_offer(cls.company)

	def test_referral_code_creation(self):
		"""Referral code is created with required fields."""
		doc = frappe.get_doc(
			{
				"doctype": "Referral Code",
				"company": self.company,
				"customer": self.customer,
				"customer_offer": self.offer.name,
			}
		)
		doc.insert(ignore_permissions=True)
		self.assertTrue(doc.name)
		self.assertTrue(doc.referral_code)
		self.assertTrue(doc.referral_name)

	def test_autoname_generates_referral_name(self):
		"""Autoname generates referral_name from customer + hash if not provided."""
		doc = frappe.get_doc(
			{
				"doctype": "Referral Code",
				"company": self.company,
				"customer": self.customer,
				"customer_offer": self.offer.name,
			}
		)
		doc.insert(ignore_permissions=True)
		self.assertIn(self.customer.strip(), doc.referral_name)
		self.assertEqual(doc.name, doc.referral_name)

	def test_autoname_respects_provided_referral_name(self):
		"""Autoname uses provided referral_name when given."""
		custom_name = f"_CustomRef{frappe.generate_hash()[:6]}"
		doc = frappe.get_doc(
			{
				"doctype": "Referral Code",
				"company": self.company,
				"customer": self.customer,
				"customer_offer": self.offer.name,
				"referral_name": custom_name,
			}
		)
		doc.insert(ignore_permissions=True)
		self.assertEqual(doc.referral_name, custom_name)
		self.assertEqual(doc.name, custom_name)

	def test_referral_code_autogenerated(self):
		"""Referral code is auto-generated as uppercase hash if not provided."""
		doc = frappe.get_doc(
			{
				"doctype": "Referral Code",
				"company": self.company,
				"customer": self.customer,
				"customer_offer": self.offer.name,
			}
		)
		doc.insert(ignore_permissions=True)
		self.assertTrue(doc.referral_code)
		self.assertEqual(len(doc.referral_code), 10)
		self.assertEqual(doc.referral_code, doc.referral_code.upper())

	def test_create_referral_code_function(self):
		"""create_referral_code factory function creates and saves a referral code."""
		doc = create_referral_code(
			company=self.company,
			customer=self.customer,
			customer_offer=self.offer.name,
		)
		self.assertTrue(doc.name)
		self.assertTrue(frappe.db.exists("Referral Code", doc.name))
